googleAnalytics = 'G-752XM86QTC'
baseURL = 'https://se-ok.github.io/'
languageCode = 'en-us'
title = 'Ad Extra'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
